import { Component, inject, ChangeDetectionStrategy } from '@angular/core';

import { NewRoomFormComponent } from '../new-room-form/new-room-form.component';
import { RestApiService } from '../services/rest-api.service';
import { JoinRoomFormComponent } from '../join-room-form/join-room-form.component';
@Component({
    selector: 'app-home',
    imports: [NewRoomFormComponent, JoinRoomFormComponent],
    template: `
  <div class="home-page-container">
    <div class="app-info">
      <h1 class="app-title">Temp Chat</h1>
      <p class="app-description">This is a real-time text chat application. A room is generated by filling out the "Create Room" form below. Select "Join Existing Room" to toggle the join form. The chat room is deleted when there are no longer any active sessions.</p>
      <p><a href="https://github.com/FunHaver/temp-chat-deploy">Source Code</a></p>
    </div>
    <div class="app-form">
      @if (!showJoinForm) {
        <app-new-room-form class="sign-in-form"></app-new-room-form>
      }
      @if (!showJoinForm) {
        <button class="toggle-form-button minor-button" (click)="toggleRoomForm()">Join Existing Room</button>
      }
      @if (showJoinForm) {
        <app-join-room-form class="sign-in-form"></app-join-room-form>
      }
      @if (showJoinForm) {
        <button class="toggle-form-button minor-button" (click)="toggleRoomForm()">Create New Room</button>
      }
    </div>
  </div>
  `,
    changeDetection: ChangeDetectionStrategy.Eager,
    styleUrls: ['./home.component.scss']
})
export class HomeComponent {
  api: RestApiService = inject(RestApiService);
  showJoinForm: boolean;

  constructor(){
    this.showJoinForm = false;
  }
  
  toggleRoomForm = () => {
    this.showJoinForm = !this.showJoinForm;
  }
}
